# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 14:29
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import invoice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Naziv klijenta')),
                ('adress', models.TextField(verbose_name='Adresa')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Dr\u017eava')),
                ('vat_id', models.CharField(blank=True, max_length=30, verbose_name='VAT')),
                ('currency', models.CharField(choices=[('HRK', 'Hrvatska Kuna'), ('EUR', 'Euro'), ('USD', 'Ameri\u010dki dolar'), ('AUD', 'Australski dolar')], default='HRK', max_length=30, verbose_name='Valuta')),
                ('default_payment_method', models.CharField(choices=[('PayPal', 'Paypal'), ('Wire-transfer', 'Wire-transfer')], default='Wire-transfer', max_length=30, verbose_name='Na\u010din pla\u0107anja')),
            ],
            options={
                'verbose_name': 'Klijent',
                'verbose_name_plural': 'Klijenti',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=invoice.models.get_latest_invoice, verbose_name='Broj ra\u010duna')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, max_length=120, verbose_name='Datum izrade ra\u010duna')),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now, max_length=120, verbose_name='Datum dospije\u0107a')),
                ('currency', models.CharField(choices=[('HRK', 'Hrvatska Kuna'), ('EUR', 'Euro'), ('USD', 'Ameri\u010dki dolar'), ('AUD', 'Australski dolar')], default='HRK', max_length=120, verbose_name='Valuta')),
                ('default_payment_method', models.CharField(choices=[('PayPal', 'Paypal'), ('Wire-transfer', 'Wire-transfer')], default='Wire-transfer', max_length=120, verbose_name='Na\u010din pla\u0107anja')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default='1.00', max_digits=12, verbose_name='Te\u010daj')),
                ('vat_value', models.DecimalField(decimal_places=2, default=Decimal('0.25'), max_digits=3, verbose_name='VAT')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice.Client', verbose_name='Klijent')),
            ],
            options={
                'verbose_name': 'Ra\u010dun',
                'verbose_name_plural': 'Ra\u010duni',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hourly', models.BooleanField(default=True, verbose_name='Obra\u010dun po satu')),
                ('description', models.CharField(max_length=300, verbose_name='Opis stavke')),
                ('additional_info', models.TextField(blank=True, max_length=300, verbose_name='Dodatni podaci')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Iznos')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cijena radnog sata')),
                ('hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Broj sati')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.Invoice')),
            ],
            options={
                'verbose_name': 'Stavka ra\u010duna',
                'verbose_name_plural': 'Stavke ra\u010duna',
            },
        ),
    ]
