# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20160419_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reverse_charge',
            field=models.BooleanField(default=False),
        ),
    ]
