# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_client_reverse_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='reverse_charge',
        ),
        migrations.AlterField(
            model_name='client',
            name='vat_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='VAT ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='VAT'),
        ),
    ]
