# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20160428_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Ra\u010dun je pla\u010den'),
        ),
    ]
