# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-20 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_paid'),
    ]

    operations = [
        migrations.RenameField('Client', 'adress', 'address')
    ]
