# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 08:32
from __future__ import unicode_literals

from django.db import migrations
import internationalflavor.vat_number.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20160620_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='vat_id',
            field=internationalflavor.vat_number.models.VATNumberField(blank=True, default='', verbose_name='VAT ID'),
        ),
    ]
